package Inheritance;
import java.util.Scanner;
public class test {
		 public static void main(String args[])
		  {
			 Scanner s=new Scanner(System.in);
			 System.out.println("Name of the book");
		    String bookName=s.next();
			 System.out.println("ISBN Number");		 
		    int isbn=s.nextInt();
		    System.out.println("Publisher name");	
		    String pubName=s.next();
		    System.out.println("Price of a book");	
		    int bprice=s.nextInt();
		    System.out.println("Number of Customers");	
		    int n=s.nextInt();
		   
		    int i;
		    for(i=1;i<=n;i++) {
				System.out.println("Details of Customer "+i);
				System.out.println("Name");
				String custName=s.next();
				System.out.println("Type of Customer (S or I or F)");
				String custType=s.next();
			}
		    Book b=new Book();//new book class for calculating total amount of the particular book
		    String custType = null;
			int total = 0;
			int totalAmnt = 0;
			b.totalAmount(totalAmnt, total, custType);//method for class book
		    Customer c=new Customer();
		    c.tot(bprice,n,totalAmnt);
		    
		    }
		  }
		class Customer{//customer class for getting customer details
			int n;int i; int totalAmnt;
			int total;
			private String custName;
			private String custType;
			public String getCustName() {
				return custName;
			}
			public void setCustName(String custName) {
				this.custName = custName;
			}
			public String getCustType() {
				return custType;
			}
			public void setCustType(String custType) {
				this.custType = custType;
			}
			int arr[]=new int[n];
			public void tot(int bprice, int n2, Object totalAmnt2) {
							
			}
			 
		}
		class Book{//details of the book are provided here
			private String bookName;
			private int isbn;
			private String pubName;
			private int totalCust;
			private int totalAmnt;
			 
			    public void totalAmount(int totalAmnt, int total, String custType) {
			    	if(custType.equals("S")==true) {
						 total=totalAmnt-(totalAmnt*50/100);
					 }
					    else if(custType.equals("I")==true) {
					    	
							total=totalAmnt-(totalAmnt*90/100);
					    }
					    else{
					    	 total=totalAmnt-(totalAmnt*75/100);
					    }	
					
				}
			public String getBookName() {
				return bookName;
			}
			
			
			public void setBookName(String bookName) {
				this.bookName = bookName;
			}
			public int getIsbn() {
				return isbn;
			}
			public void setIsbn(int isbn) {
				this.isbn = isbn;
			}
			public String getPubName() {
				return pubName;
			}
			public void setPubName(String pubName) {
				this.pubName = pubName;
			}//getters and setters auto-generated by right-clicking and source-->generate getters and setters
			public int getTotalCust() {
				return totalCust;
			}
			public void setTotalCust(int totalCust) {
				this.totalCust = totalCust;
			}
			public int getTotalAmnt() {
				return totalAmnt;
			}
			public void setTotalAmnt(int totalAmnt) {
				this.totalAmnt = totalAmnt;
			}
		}